name: 🚀 Deploy to VPS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 🔑 Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: 173.249.54.81
          username: root
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /opt/gff-erp-
            git pull origin main
            npm install
            npm run build
            pm2 restart gff-erp || pm2 start npm --name "gff-erp" -- start
